# Generated by Django 4.2.13 on 2024-08-29 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal_app', '0002_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_content_en_us',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_title_en_us',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('PO', 'Политика'), ('SP', 'Спорт'), ('EC', 'Экономика'), ('SC', 'Наука'), ('TE', 'Технологии'), ('FI', 'Фантастика'), ('MY', 'Мистика'), ('FA', 'Фэнтези'), ('DE', 'Детектив'), ('HI', 'История')], default='PO', max_length=2),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='NewsPortal_app.post'),
        ),
    ]
